language: php
php:
    - hhvm
before_script:
    - export TZ='UTC'
    - composer self-update
    - composer install
script: "phpunit --colors --testsuite UnitTest"
script: "phpunit --colors --testsuite WebTest"
